exclude: |
    (?x)^(
        .*coverage/.*|
        .*coverage_badge/.*
        .*dist/.*
    )$
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: detect-private-key
  - id: debug-statements
  - id: pretty-format-json
    exclude: |
      (?x)^(
          .*devcontainer.*|
          .*vscode.*
      )$
    args: ['--autofix']
  - id: mixed-line-ending
    args: ['--fix=lf']
  - id: check-added-large-files
    args: ['--maxkb=5000']

- repo: https://gitlab.com/smop/pre-commit-hooks
  rev: 'v1.0.0'
  hooks:
  - id: check-poetry

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.0.0'
  hooks:
  - id: mypy
    args: ["--install-types", "--non-interactive", "--ignore-missing-imports", "--explicit-package-bases"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.269
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
